import { expect, test } from "@playwright/test";
import { battleSuccessFixture } from "./fixtures/battle-success.js";
import { catalogFixture } from "./fixtures/catalog.js";
import { fillMinimalFormation } from "./support/formation.js";
import { mockCatalog, mockSimulationSequence } from "./support/mock-api.js";

// docs/ui-design/06_UIテスト戦略.md §7 (Visual regression): 1440×900と
// 390×844を最低baselineとし、動的時刻・Battle ID・画像取得を固定して撮影する。
// This fixture set has no rendered wall-clock timestamp and no imageMap (so
// every DefinitionImage renders its deterministic initials fallback, never a
// network image), so no additional masking is required beyond disabling CSS
// animations.
//
// Baseline PNGs are generated by CI (ubuntu-latest, the same runner PRs are
// judged against), not on a contributor's local OS, because Chromium's text
// anti-aliasing rendering is not pixel-identical across platforms. See the
// PR description for the generation procedure.
//
// Every test title carries an "@visual" tag: `pnpm run test:e2e` (the
// default local/CI functional command) excludes it via --grep-invert, and
// `pnpm run test:e2e:visual` (CI-only, see .github/workflows/pr.yml) selects
// it via --grep. Without this split, a contributor running the default
// command on macOS/Windows would always fail here for lacking a
// -chromium-darwin.png/-chromium-win32.png baseline that was never meant to
// exist (review: PR #124).

test.beforeEach(async ({ page }) => {
  await mockCatalog(page, { status: 200, body: catalogFixture });
});

test("desktop (1440x900) idle formation screen matches the visual baseline @visual", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("./");
  await expect(page.getByRole("heading", { name: /ALLY FORMATION/ })).toBeVisible();

  await expect(page).toHaveScreenshot("desktop-1440x900-idle.png", {
    fullPage: true,
    animations: "disabled",
  });
});

test("desktop (1440x900) battle result screen matches the visual baseline @visual", async ({
  page,
}) => {
  await mockSimulationSequence(page, [{ status: 200, body: battleSuccessFixture }]);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("./");
  await fillMinimalFormation(page, "アライアルファ", "エネミーアルファ");
  await page.getByRole("button", { name: "戦闘を開始" }).click();
  await expect(page.getByText("戦闘が完了しました。")).toBeVisible();

  await expect(page).toHaveScreenshot("desktop-1440x900-result.png", {
    fullPage: true,
    animations: "disabled",
  });
});

test("mobile (390x844) idle formation screen matches the visual baseline @visual", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("./");
  await expect(page.getByRole("heading", { name: /ALLY FORMATION/ })).toBeVisible();

  await expect(page).toHaveScreenshot("mobile-390x844-idle.png", {
    fullPage: true,
    animations: "disabled",
  });
});
